<a href="https://colab.research.google.com/github/Madhuanabala/deepak-bhaiya_new/blob/model-validation/MD_for_unknown.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline


! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip -o fingerprints_xml.zip

--2025-08-22 11:48:26--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2025-08-22 11:48:27--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘fingerprints_xml.zip’

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2025-08-22 11:48:27 (57.4 MB/s) - ‘fingerprints_xml.zip’ saved [10871/10871]

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [2]:
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [4]:
fp = dict(zip(FP_list, xml_files))
fp

{'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml',
 'Substructure': 'SubstructureFingerprinter.xml'}

In [5]:
df = pd.read_excel('/content/unknown.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4020 entries, 0 to 4019
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   np_id                       4020 non-null   object
 1   InChI                       4020 non-null   object
 2   InChIKey                    4020 non-null   object
 3   SMILES                      4020 non-null   object
 4   Similarity_to_Reference(%)  4020 non-null   float64
dtypes: float64(1), object(4)
memory usage: 157.2+ KB

In [6]:
df = pd.concat( [df['SMILES']], axis=1 )
df.to_csv('molecule.smi', sep='\t', index=False, header=False)
df

                                                 SMILES
0     CC(C)CCN1Cc2cc3c(cc2[C@@]24C=C[C@H](C[C@@H]2N(...
1     COc1c2c(cc3c1OCO3)O[C@@]([C@@H]([C@H](C2=O)C(=...
2     CC(=O)OCn1c2ccccc2c2c([C@@H]3[C@H](CC[C@](C)([...
3            C/C(=N\n1c(C)nc2cc3c(cc2c1=O)OCO3)/c1cccs1
4     CC(C)C(=N[C@@H]1CCCN1C(=O)[C@H]1[C@H](c2ccccc2...
...                                                 ...
4015                  CN1C2=C(C(=N)N(C1=O)C)NC(=O)N2.Cl
4016          CN1C(=[NH2+])C2=C(NC1=O)N(C)C(=O)N2.[Cl-]
4017  CC(C)C1NC(=O)[C@H](CC2=CC=CC=C2)NC(=O)[C@@H]2N...
4018  CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...
4019  CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)NCC(=O)N[...

[4020 rows x 1 columns]

In [7]:
!pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 92.9 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

In [8]:
from padelpy import padeldescriptor

fingerprint = 'MACCS'

fingerprint_output_file = ''.join([fingerprint,'.csv'])
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='molecule.smi',
                d_file=fingerprint_output_file,

                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=1,
                removesalt=True,
                log=True,
                fingerprints=True)

In [9]:
descriptors = pd.read_csv(fingerprint_output_file)
descriptors

,Name,MACCSFP1,MACCSFP2,MACCSFP3,MACCSFP4,MACCSFP5,MACCSFP6,MACCSFP7,MACCSFP8,MACCSFP9,...,MACCSFP157,MACCSFP158,MACCSFP159,MACCSFP160,MACCSFP161,MACCSFP162,MACCSFP163,MACCSFP164,MACCSFP165,MACCSFP166
0,AUTOGEN_molecule_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
1,AUTOGEN_molecule_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
2,AUTOGEN_molecule_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
3,AUTOGEN_molecule_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
4,AUTOGEN_molecule_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4015,AUTOGEN_molecule_4016,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
4016,AUTOGEN_molecule_4017,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
4017,AUTOGEN_molecule_4018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
4018,AUTOGEN_molecule_4019,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
4019,AUTOGEN_molecule_4020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0

In [11]:

original_df = pd.read_excel('/content/unknown.xlsx')


descriptors_df = pd.read_csv(fingerprint_output_file)


final_df = pd.concat([original_df[['SMILES']], descriptors_df], axis=1)

#
final_output_file = f"{fingerprint}_with_SMILES.csv"
final_df.to_csv(final_output_file, index=False)

print(f"Final file saved as {final_output_file}")

Final file saved as MACCS_with_SMILES.csv